### ISSUE TITLE
[Bug] Default roles are not showing in the UI

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6-UI#37] opened 2022-08-30 09:03 UTC
**Describe the bug**
Default roles are not showing in the UI. However when using the Python client I was able to retrieve them.

**To Reproduce**
![image](https://user-images.githubusercontent.com/15981243/187396030-4ae9238c-14f7-4a29-8798-739e5119122a.png)

**Comment by bartvanb** [comment] 2022-09-21 12:00
Aaaand transfered the issue back (it was a UI issue after all).

Part of this issue has been resolved by #36, which caused the wrong request to be sent to the server (`/role?include_root=True&organization_id=null` where the `null` part should be a number.

Now, it is still not showing all the default roles, but that is actually not a bug (!). 
The root role on petronas apparently does not have permission to view ports, and the default roles do. Therefore, a root user is simply not allowed to assign any of these roles as they have permissions the root user does not.

**Closed as completed by bartvanb** 2022-09-21 12:00 UTC
Labels: bug
